package mx.edu.utxj.pye.hallazgos.pojos;
// Generated 10/03/2021 11:22:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TbUsuario generated by hbm2java
 */
public class TbUsuario  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String usuario;
     private String password;
     private String rol;
     private Set<TbHallazgo> tbHallazgosForEvalua = new HashSet<TbHallazgo>(0);
     private Set<TbHallazgo> tbHallazgosForAsignada = new HashSet<TbHallazgo>(0);
     private Set<TbHallazgo> tbHallazgosForReporta = new HashSet<TbHallazgo>(0);

    public TbUsuario() {
    }

    public TbUsuario(String nombre, String usuario, String password, String rol, Set<TbHallazgo> tbHallazgosForEvalua, Set<TbHallazgo> tbHallazgosForAsignada, Set<TbHallazgo> tbHallazgosForReporta) {
       this.nombre = nombre;
       this.usuario = usuario;
       this.password = password;
       this.rol = rol;
       this.tbHallazgosForEvalua = tbHallazgosForEvalua;
       this.tbHallazgosForAsignada = tbHallazgosForAsignada;
       this.tbHallazgosForReporta = tbHallazgosForReporta;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set<TbHallazgo> getTbHallazgosForEvalua() {
        return this.tbHallazgosForEvalua;
    }
    
    public void setTbHallazgosForEvalua(Set<TbHallazgo> tbHallazgosForEvalua) {
        this.tbHallazgosForEvalua = tbHallazgosForEvalua;
    }
    public Set<TbHallazgo> getTbHallazgosForAsignada() {
        return this.tbHallazgosForAsignada;
    }
    
    public void setTbHallazgosForAsignada(Set<TbHallazgo> tbHallazgosForAsignada) {
        this.tbHallazgosForAsignada = tbHallazgosForAsignada;
    }
    public Set<TbHallazgo> getTbHallazgosForReporta() {
        return this.tbHallazgosForReporta;
    }
    
    public void setTbHallazgosForReporta(Set<TbHallazgo> tbHallazgosForReporta) {
        this.tbHallazgosForReporta = tbHallazgosForReporta;
    }




}


